#!groovy

// Generated by IBM TransformationAdvisor
// Mon May 13 12:52:34 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}